print ("You are -name-")
name = str(input("Pick a Name: "))
print(f"{name} is -adjective-")
adj = str(input("Pick an Adjective: "))
print(f"{name} has an issue and wants to -verb- it")
verb = str(input("Pick a verb: "))
print(f"{name} can {verb} it in so many different ways! \nHe wants to choose just -number- different ways though.")
num = int(input("Pick a number: "))
print(f"But in the end {name} hates himself because of the choices.")
print(f"Here is your final Mad Lib about {name}:")
print (f"You are {name}")
print(f"{name} is {adj}")
print(f"{name} has an issue and wants to {verb} it")
print(f"{name} can {verb} it in so many different ways! \nHe wants to choose just {num} different ways though.")
print(f"But in the end {name} hates himself because of the choices.")